/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospetal;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class user extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    public user() {
        initComponents();
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        addUser = new javax.swing.JButton();
        haveUser = new javax.swing.JButton();
        confirmPass = new javax.swing.JButton();
        pass = new javax.swing.JButton();
        name = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        pageTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setLayout(null);

        addUser.setBackground(new java.awt.Color(0, 153, 204));
        addUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addUser.setForeground(new java.awt.Color(0, 0, 204));
        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospetal/Images/Add_Employee.png"))); // NOI18N
        addUser.setText("أضافه مستخدم");
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });
        jPanel2.add(addUser);
        addUser.setBounds(350, 510, 197, 60);

        haveUser.setBackground(new java.awt.Color(0, 153, 204));
        haveUser.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        haveUser.setForeground(new java.awt.Color(0, 0, 255));
        haveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospetal/Images/Staff.png"))); // NOI18N
        haveUser.setText("أنا مستخدم أصلا");
        haveUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveUserMouseClicked(evt);
            }
        });
        jPanel2.add(haveUser);
        haveUser.setBounds(340, 600, 220, 60);

        confirmPass.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        confirmPass.setForeground(new java.awt.Color(204, 0, 0));
        confirmPass.setText("أعد كلمه السر");
        jPanel2.add(confirmPass);
        confirmPass.setBounds(520, 410, 120, 40);

        pass.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        pass.setForeground(new java.awt.Color(204, 0, 0));
        pass.setText("كلمه السر");
        jPanel2.add(pass);
        pass.setBounds(520, 320, 120, 40);

        name.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(204, 0, 0));
        name.setText("اسم المستخدم");
        jPanel2.add(name);
        name.setBounds(520, 230, 120, 40);

        password.setForeground(new java.awt.Color(0, 0, 204));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel2.add(password);
        password.setBounds(290, 320, 210, 40);

        confirmPassword.setForeground(new java.awt.Color(0, 0, 204));
        confirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel2.add(confirmPassword);
        confirmPassword.setBounds(290, 410, 210, 40);

        user.setForeground(new java.awt.Color(0, 0, 255));
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel2.add(user);
        user.setBounds(290, 230, 210, 40);

        pageTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(204, 0, 0));
        pageTitle.setText("أضافه مستخدم جديد");
        jPanel2.add(pageTitle);
        pageTitle.setBounds(340, 130, 240, 43);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospetal/Images/bk2.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), null, new java.awt.Color(0, 255, 102), new java.awt.Color(255, 255, 51)));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 90, 1000, 630);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel3.setText("Hospital MANAGEMENT SYSTEM ");

        logOut.setBackground(new java.awt.Color(255, 255, 255));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospetal/Images/logout.png"))); // NOI18N
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 88);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private static boolean isConfirmPassword(char[] passW, char[] confPassW){
        boolean isCorrect = true;
        if(passW.length != confPassW.length){
             isCorrect = false;
        } else{
            for(int i=0; i< passW.length;i++){
                if (passW[i] != confPassW[i]){
                    isCorrect = false;
                }
            }        
        }        
        return isCorrect;
    }
    private void saveUser(String userName, char[] userPassword) {
        try{
            File file=new File(".\\src\\"+userName+".txt");
            if(file.exists()){
                JOptionPane.showMessageDialog(null, "المستخدم موجود أصلا");
                user.setText("");
                password.setText("");
                confirmPassword.setText("");
                return;
            }else{
                file.createNewFile() ;
                FileWriter fw =new FileWriter(file.getAbsoluteFile()) ;
                BufferedWriter bw = new BufferedWriter(fw);
                for(int i=0;i<userPassword.length;i++){
                    bw.append(userPassword[i]);
                }
                bw.close();
                fw.close();
                new MainMenu().setVisible(true);
                this.dispose();
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logOutMouseClicked

    private void haveUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveUserMouseClicked
        // TODO add your handling code here:
        new logIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_haveUserMouseClicked

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked
        // TODO add your handling code here:
        if(isConfirmPassword(password.getPassword(),confirmPassword.getPassword())){
            saveUser(user.getText(),password.getPassword());
        }else{
            JOptionPane.showMessageDialog(null, "كلمه السر غير متطابقه");
        }
        
    }//GEN-LAST:event_addUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JButton confirmPass;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JButton haveUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOut;
    private javax.swing.JButton name;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton pass;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
